@host = http://localhost:5158
@token = eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMWUyOGQ0ZS0zOGUzLTQ4N2EtYTI3Yi00ODQ5ZTkyOTk2NTcifQ.eyJleHAiOjE3ODA5OTIyMjUsImlhdCI6MTc4MDk5MDQyNSwianRpIjoiOGQzZTk1ZDMtMTYzOC00MjlhLWIxZGUtM2M0YmUyYmI0NWYxIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9DaXR5Q2FyZSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvQ2l0eUNhcmUiLCJzdWIiOiI1OTZkNTdmMC02ODIyLTQyMzItOTZhNC05ODExMzQzMjE0MjkiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiY2l0eWNhcmUtd2ViIiwic2Vzc2lvbl9zdGF0ZSI6IjQ4YTVhZTE1LTIzNjMtNGEwYi04ZTM4LWI0ZDExNjAxNjdkYSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjQ4YTVhZTE1LTIzNjMtNGEwYi04ZTM4LWI0ZDExNjAxNjdkYSJ9.O_CJTJt-49egR49tfcQwIhIZJJt98asYWmGlcluSEF0DtNjM88UgC4dF5JrZ3ThH7RsKxbvvvqSqTUUWrdesCw"
@incidentId = 123

### Récupérer le Token depuis Keycloak
POST http://localhost:8080/realms/CityCare/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=citycare-web&
username=testadmin&
password=test

### Test Santé / Weatherforecast
GET {{host}}/weatherforecast/
Accept: application/json

### Endpoint Profil
GET {{host}}/auth/me
Authorization: Bearer {{token}}
Accept: application/json

### Créer un signalement
POST {{host}}/incidents
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Nouveau signalement",
  "description": "Description du problème",
  "latitude": 45.8650,
  "longitude": 4.8357
}

### Lister avec filtres + pagination 
GET {{host}}/incidents?page=1&pageSize=10&status=open
Accept: application/json
Authorization: Bearer {{token}}

### Détail complet d'un incident
GET {{host}}/incidents/{{incidentId}}
Accept: application/json
Authorization: Bearer {{token}}

### Aperçu léger pour popup
GET {{host}}/incidents/{{incidentId}}/preview
Accept: application/json
Authorization: Bearer {{token}}