@host = http://localhost:5158
@token = eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMWUyOGQ0ZS0zOGUzLTQ4N2EtYTI3Yi00ODQ5ZTkyOTk2NTcifQ.eyJleHAiOjE3NzY5NDk4MjksImlhdCI6MTc3Njk0ODAyOSwianRpIjoiNzU5NzdiZWYtNzZiNC00YTIyLTgxYWEtMTllMmFhYjRhZGNjIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9DaXR5Q2FyZSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvQ2l0eUNhcmUiLCJzdWIiOiI1OTZkNTdmMC02ODIyLTQyMzItOTZhNC05ODExMzQzMjE0MjkiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoiY2l0eWNhcmUtd2ViIiwic2Vzc2lvbl9zdGF0ZSI6ImQyNDcxZjZhLTM3MDItNDk5Zi05ZmE4LTIwNDFjN2NjNTE3YSIsInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImQyNDcxZjZhLTM3MDItNDk5Zi05ZmE4LTIwNDFjN2NjNTE3YSJ9.fLK32istiaYAhXzogVn3JA8nIDOP6gGoA4tmhosAxT3bpAGkbdDOTwg6GyN0QIZF-PNfKaRTuQp35Z2lzAy__w
@incidentId = 123

### Récupérer le Token depuis Keycloak
POST http://localhost:8080/realms/CityCare/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=citycare-web&
username=testadmin&
password=test

### Test Santé / Weatherforecast
GET {{host}}/weatherforecast/
Accept: application/json

### Endpoint Profil
GET {{host}}/auth/me
Authorization: Bearer {{token}}
Accept: application/json

### Créer un signalement
POST {{host}}/incidents
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Nouveau signalement",
  "description": "Description du problème",
  "latitude": 45.7640,
  "longitude": 4.8357
}

### Lister avec filtres + pagination 
GET {{host}}/incidents?page=1&pageSize=10&status=open
Accept: application/json
Authorization: Bearer {{token}}

### Détail complet d'un incident
GET {{host}}/incidents/{{incidentId}}
Accept: application/json
Authorization: Bearer {{token}}

### Aperçu léger pour popup
GET {{host}}/incidents/{{incidentId}}/preview
Accept: application/json
Authorization: Bearer {{token}}