name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /home/stagiaire/city-care
          git fetch origin
          git checkout main
          git reset --hard origin/main
          docker compose up -d --build
          docker image prune -f